name: easyvizar-detect
base: core18
version: "0.1"
summary: Object detection for EasyVizAR headsets
description: |
  This module automatically performs object detection on images
  uploaded to the EasyVizAR edge server.

grade: stable
confinement: strict

apps:
  detect:
    command: bin/detect
    daemon: simple
    environment:
      DATA_PATH: $SNAP/easyvizar
      MODEL_DIR: $SNAP_DATA/models
      PYTHONPATH: $SNAP_DATA/lib/python3.8/site-packages
      TORCH_HOME: $SNAP_DATA
      VIZAR_SERVER: localhost:5000
    plugs:
      - network

architectures:
  - build-on: amd64
  - build-on: arm64

hooks:
  install:
    plugs: [network]
  post-refresh:
    plugs: [network]

parts:
  deps:
    plugin: nil
    stage-packages:
      - libgl1
      - libice6
      - libsm6
      - libx11-6
      - libxext6
      - libxcb1
      - try:
        - libcuda1-384
        - libcudart10.1

  setup:
    plugin: dump
    source: setup
    organize:
      '*.txt': setup/

  detect:
    plugin: python
    source: .
    build-packages:
      - python3-dev
    stage-packages:
      - python3
      - python3-pip
    requirements:
      - requirements.txt

plugs:
  data:
    interface: content
    content: data
    target: $SNAP/easyvizar
    default-provider: easyvizar-edge
