#!/bin/sh
#
# This script does some one-time tasks when the snap is installed for the first
# time.  After the first install, it will not be run again for version upgrades
# unless the snap is completely removed and reinstalled.
#

tmp_dir="$SNAP_COMMON/pip-install"
install_dir="$SNAP_DATA/python-packages"

log_file="$SNAP_COMMON/install.log"
error_file="$SNAP_COMMON/errors.log"

# Some devices may have a tmpfs filesystem that is too small to unpack torch
# for installation, which results in "No space left on device" errors.
export TMPDIR="$tmp_dir"

echo "Running snap install hook..." >$log_file

# -E flag ignores PYTHONPATH, which points to our initially empty install directory.
"$SNAP/bin/python3" -E -m pip install --no-cache-dir --target "$install_dir" --requirement "$SNAP/setup/requirements.$SNAP_ARCH.txt" >>"$log_file" 2>"$error_file"

if $? ; then
    echo "Python packages installed successfully" >>"$log_file"
else
    echo "Python packages were NOT installed, check $error_file" >>"$log_file"
fi
