#!/bin/sh
#
# This script does some one-time tasks when the snap is installed for the first
# time.  After the first install, it will not be run again for version upgrades
# unless the snap is completely removed and reinstalled.
#

install_dir="$SNAP_DATA"
torch_url=https://download.pytorch.org/whl/torch_stable.html

python3 -m pip install --target "$SNAP_DATA" --requirements "$SNAP/setup/requirements.$SNAP_ARCH.txt"
