#!/bin/sh
#
# This script does some one-time tasks when the snap is installed for the first
# time.  After the first install, it will not be run again for version upgrades
# unless the snap is completely removed and reinstalled.
#

install_dir="$SNAP_DATA"
torch_url=https://download.pytorch.org/whl/torch_stable.html

if [ "$SNAP_ARCH" == "amd64" ]; then
    python3 -m pip install --find-links "$torch_url" --target "$SNAP_DATA" "torch==1.8.1+cu101"
    python3 -m pip install --find-links "$torch_url" --target "$SNAP_DATA" "torchvision==0.9.1+cu101"
else
    python3 -m pip install --find-links "$torch_url" --target "$SNAP_DATA" "torch>=1.7.0,<1.12.0"
    python3 -m pip install --find-links "$torch_url" --target "$SNAP_DATA" "torchvision>=0.8.1,<0.13.0"
fi
